dist: bionic
before-install:
    - sudo apt-get update
    - sudo apt-get -y install build-essential gfortran python3-dev libopenmpi-dev openmpi-bin libgsl-dev cmake libfftw3-3 libfftw3-dev libgmp3-dev libmpfr6 libmpfr-dev libhdf5-serial-dev hdf5-tools git
    - export PYTHONPATH=$PYTHONPATH:$(pwd)/src/
language: python
python:
    - "3.8"
install:
    - pip install numpy nose docutils mpi4py h5py wheel
    - pip install scipy astropy jupyter pandas seaborn
    - pip install rebound
    - pip install amuse-framework
    - pip install amuse-ph4 amuse-kepler amuse-sse amuse-seba amuse-smalln
    - pip install guppy3

script:
    - python sim_cluster.py -g -p 5 -s 10 -c Leonis -w 4.5 -T 11 -S Leonis -b
